-- Business insights and data analysis for the data 

-- Q1 what is the total revenue generated by male vs female customers?
select gender , sum(purchase_amount)
from customer 
GROUP BY 1;


--Q2 which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id,purchase_amount 
FROM customer 
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer )
AND discount_applied ilike 'yes';


--Q3 which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS average_product_rating 
FROM customer 
GROUP BY 1 
ORDER BY 2 DESC 
LIMIT 5;


--Q4: Do customers who choose Express shipping tend to spend more on average than those who choose Standard shipping?
SELECT shipping_type, AVG(purchase_amount) 
FROM customer 
WHERE shipping_type IN ('Standard', 'Express') 
GROUP BY 1;


--Q5How do subscribed customers compare to non-subscribed customers in terms of total count, average spending, and total revenue contribution?
SELECT subscription_status, 
       COUNT(customer_id) AS total_customers, 
       AVG(purchase_amount) AS average_spend, 
       SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY 1
ORDER BY 4 DESC, 3 DESC;


--Q6Which products rely the most on discounts to sell (i.e., have the highest percentage of transactions where a discount was applied)?
SELECT item_purchased, 
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*) AS discount_rate 
FROM customer 
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 5;


--Q7What is the breakdown of our customer base into "New" (1 purchase), "Returning" (2-10 purchases), and "Loyal" (>10 purchases) segments?
WITH customer_type AS (
    SELECT customer_id, previous_purchases, 
           CASE 
               WHEN previous_purchases = 1 THEN 'New' 
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
               ELSE 'Loyal' 
           END AS customer_segment 
    FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers 
FROM customer_type 
GROUP BY 1;


--Q8What are the top 3 best-selling items within each specific product category?
WITH item_counts AS (
    SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank 
    FROM customer 
    GROUP BY 1,2
)
SELECT item_rank, category, item_purchased, total_orders 
FROM item_counts 
WHERE item_rank <= 3;


--Q9Are our frequent repeat buyers (those with more than 5 past purchases) actually signing up for the subscription service?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers 
FROM customer 
WHERE previous_purchases > 5 
GROUP BY 1;


--Q10 What is the revenue contribution by each group ? 	   
SELECT age_group ,
	   CONCAT(ROUND((sum(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer))*100 ,2),'%')  AS revenue_perctange
FROM customer 
GROUP BY 1